# fly.toml app configuration file generated for cdc-connector on 2025-12-17T16:48:22+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'cdc-connector'
primary_region = 'fra'

[build]
  dockerfile = 'connectors/Dockerfile'
  build-context = 'connectors'

[http_service]
  internal_port = 8083
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  [[http_service.checks]]
    grace_period = "60s"
    interval = "30s"
    method = "GET"
    timeout = "5s"
    path = "/"

[[vm]]
  memory = '8gb'
  cpus = 2
  memory_mb = 2048
